name: "Familjecentralen"
version: "2.2.4"
slug: "familjecentralen"
description: "Ã–rtendahls Familjecentral - Kalender och Sysslor"
url: "https://github.com/S1887/Familjecentralen"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ingress: true
ingress_port: 3001
map:
  - config:rw
options: {}
schema: {}
