name: "Örtendahls Familjecentral"
version: "3.0.37"
slug: "ortendahls_familjecentral"
description: "Örtendahls Familjecentral - Kalender och Sysslor"
url: "https://github.com/S1887/Familjecentralen"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ingress: true
ingress_port: 3001
ingress_stream: true
panel_icon: mdi:calendar-heart
panel_title: Familjecentralen
ports:
  3001/tcp: 3001
map:
  - config:rw
options: {}
schema: {}
