name: "Familjecentralen-Dev"
version: "0.0.1"
slug: "familjecentralen-dev"
description: "EXPERIMENTELL - Ã–rtendahls Familjecentral"
url: "https://github.com/S1887/Familjecentralen"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
ingress: true
ingress_port: 3002
ingress_entry: /
ports:
  3002/tcp: 3002
map:
  - config:rw
options: {}
schema: {}
